export * from './load';
export * from './add';
export * from './remove';
export * from './load-by-id';
export * from './load-by-categoria';
export * from './update';
export * from './foto-update';
export * from './foto-add';
export * from './foto-remove';
